### ISSUE TITLE
Address did:peer:2 spec changes

### ISSUE THREAD

**Issue by FabioPinheiro** [input-output-hk/atala-prism-wallet-sdk-swift#105]
### Is this a regression?

No

### Description

Address the changes on the `did:peer` specs made by [this PR](https://github.com/decentralized-identity/peer-did-method-spec/pull/62)

The work of how to fix the libraries and applications to address those changes can be found [here](https://github.com/decentralized-identity/peer-did-method-spec/issues/64), and is also is been tracked.

**Comment by goncalo-frade-iohk** [comment]
Here is the PR for it:

https://github.com/input-output-hk/atala-prism-wallet-sdk-swift/pull/120

**Comment by mkbreuningIOHK** [comment]
@goncalo-frade-iohk , as the PR #120 , this should be closed, right? Can you confirm?

**Comment by FabioPinheiro** [comment]
Yes let's close this
