### ISSUE TITLE
Not able to Submit Archive with Swift SDK SPM

### ISSUE THREAD

**Issue by coveloper** [input-output-hk/atala-prism-wallet-sdk-swift#127]
### Is this a regression?

Yes

### Description

To replicate:
1. Use Xcode 15.3 or 15.2, create new project (iOS or MultiPlatform).  
2. Set deployment target to anything, 15, 16, or 17
3. Add Swift SDK using SPM.  
4. Archive project (should build)
5. Submit to AppStoreConnect:
6. Observe Error returned:
<img width="690" alt="Screenshot 2024-03-19 at 7 34 33 PM" src="https://github.com/input-output-hk/atala-prism-wallet-sdk-swift/assets/195326/6c941f8c-b7c8-4f69-a519-f8696f77e6fe">

### Please provide the exception or error you saw

```true
'Invalid Bundle.  The bundle ____/Frameworks/ApolloLibrary.framework does not support the minimum OS Version specified in the Info.plist (ID: $someID)
```

### Please provide the environment you discovered this bug in

```true
Xcode 15.3 iOS project and MultiPlatform project (iOS/Mac), with deployment target of iOS 15/16/17

This happens with Swift SDK v4.0.1 and v5.0.0
```

### Anything else?

I'm not able to ship an app with the Swift SDK to TestFlight.  I was able to do this with earlier versions of the SDK but it's been about a year since I've tried.

**Comment by coveloper** [comment]
Found this, maybe it's an Xcode 15.3 thing:  https://forums.developer.apple.com/forums/thread/748177

**Comment by coveloper** [comment]
I had same issue with Xcode 15.2

**Comment by coveloper** [comment]
More complaints about 15.3:  https://www.reddit.com/r/swift/comments/1bd7kxj/swift_ios_cannot_upload_to_testflight/

**Comment by goncalo-frade-iohk** [comment]
@coveloper this is fixed right or you still have problems?

**Comment by essbante-io** [comment]
This issue has been addressed and is now considered solved. If you have further questions or related concerns, please open a new issue.
