### ISSUE TITLE
Can we make DidDoc struct convertible to json?

### ISSUE THREAD

**Issue by AlexAndrei98** [input-output-hk/atala-prism-wallet-sdk-swift#63]
I am currently trying to get back a string that looks like json from the diddoc struct but having a hard time since the struct is not codable. Would it make sense to make a change that way or what is a better way to convert a struct to a string?

**Comment by essbante-io** [comment]
This Issue hasn't seen activity in a while. I'm closing it for now, but if this work is still needed, please feel free to reopen it.
